#!/usr/bin/env bash
# scripts/bump.sh — release-readiness version-bump gate.
#
#   scripts/bump.sh --check [--base-ref <branch>]
#
# --check ONLY. There is no --apply: in this repo, version bumps are applied
# by hand as part of the release PR (edit plugin/.claude-plugin/plugin.json
# and plugin/.claude-plugin/marketplace.json — "the plugin pair" — then run
# ./build-plugin.sh to resync the generated root .claude-plugin/marketplace.json).
# No automated executor writes the version today; if one is added later, give
# it its own flag rather than repurposing this file's read-only contract.
#
# Doctrine — dual mode by PR base (GITHUB_BASE_REF on a pull_request event):
#   base=main:    "shipped" (plugin/ + .claude-plugin/) changed vs origin/main
#                 -> version must be STRICTLY GREATER than origin/main's.
#                 unchanged -> no-op, always OK.
#   base=develop: version must EQUAL origin/main's version. develop never
#                 carries a bump itself — a release PR (develop -> main) is
#                 what advances the version, and back-merging main into
#                 develop afterwards self-heals the equality.
# Both modes compare against origin/main ONLY. --base-ref selects which
# doctrine applies; it is not a ref this script diffs against (origin/develop
# is never fetched or read).
#
# Waiver: HAS_NO_RELEASE=true (wired from the `no-release` PR label by the
# calling workflow) skips the gate entirely. Dormant today — the label does
# not exist on the board yet.
set -euo pipefail

readonly PLUGIN_JSON="plugin/.claude-plugin/plugin.json"
readonly PLUGIN_MARKETPLACE_JSON="plugin/.claude-plugin/marketplace.json"
readonly ROOT_MARKETPLACE_JSON=".claude-plugin/marketplace.json"
readonly SHIPPED_PATHS=(plugin/ .claude-plugin/)
readonly BASE_REMOTE_REF="origin/main"

die() { echo "bump: $*" >&2; exit 1; }

usage() { die "usage: bump.sh --check [--base-ref <branch>]"; }

# --- version IO (python3: robust read of the two manifest shapes) ---
_plugin_json_version() {  # <path> — top-level "version"
  python3 -c 'import json,sys; print(json.load(open(sys.argv[1]))["version"])' "$1"
}
_marketplace_json_version() {  # <path> — plugins[0].version
  python3 -c 'import json,sys; print(json.load(open(sys.argv[1]))["plugins"][0]["version"])' "$1"
}
_plugin_json_version_at() {  # <git-ref> — plugin.json's "version" as of that ref
  git show "${1}:${PLUGIN_JSON}" | python3 -c 'import json,sys; print(json.load(sys.stdin)["version"])'
}

# --- semver (pure bash, portable) ---
require_semver() {  # accept only plain X.Y.Z integers — no leading zeros, no pre-release/build suffixes
  printf '%s' "$1" | grep -Eq '^(0|[1-9][0-9]*)(\.(0|[1-9][0-9]*)){2}$' \
    || die "version '$1' is not plain X.Y.Z (leading zeros and pre-release/build suffixes unsupported)"
}
semver_gt() {  # "is A > B ?" -> exit 0 if yes
  local aM aN aP bM bN bP
  IFS=. read -r aM aN aP <<<"$1"
  IFS=. read -r bM bN bP <<<"$2"
  [ "$aM" -gt "$bM" ] && return 0; [ "$aM" -lt "$bM" ] && return 1
  [ "$aN" -gt "$bN" ] && return 0; [ "$aN" -lt "$bN" ] && return 1
  [ "$aP" -gt "$bP" ]
}

ensure_base() {
  git fetch -q origin "main:refs/remotes/origin/main" 2>/dev/null \
    || git fetch -q origin main 2>/dev/null || true
  git rev-parse --verify -q "${BASE_REMOTE_REF}" >/dev/null \
    || die "cannot resolve ${BASE_REMOTE_REF} (fetch failed?)"
}

shipped_changed() { ! git diff --quiet "${BASE_REMOTE_REF}" -- "${SHIPPED_PATHS[@]}"; }

# All three manifests must carry the identical version. The root marketplace.json
# is generated by build-plugin.sh Step 5c — disagreement means someone hand-edited
# it, or edited the plugin pair and forgot to rebuild.
check_manifests_agree() {
  [ -f "$PLUGIN_JSON" ] || die "missing $PLUGIN_JSON — run from the repo root"
  [ -f "$PLUGIN_MARKETPLACE_JSON" ] || die "missing $PLUGIN_MARKETPLACE_JSON — run from the repo root"
  [ -f "$ROOT_MARKETPLACE_JSON" ] || die "missing $ROOT_MARKETPLACE_JSON — run from the repo root"

  local canonical plugin_mkt_v root_mkt_v
  canonical="$(_plugin_json_version "$PLUGIN_JSON")"
  require_semver "$canonical"
  plugin_mkt_v="$(_marketplace_json_version "$PLUGIN_MARKETPLACE_JSON")"
  root_mkt_v="$(_marketplace_json_version "$ROOT_MARKETPLACE_JSON")"

  local mismatched=()
  [ "$plugin_mkt_v" = "$canonical" ] \
    || mismatched+=("$PLUGIN_MARKETPLACE_JSON has $plugin_mkt_v")
  [ "$root_mkt_v" = "$canonical" ] \
    || mismatched+=("$ROOT_MARKETPLACE_JSON has $root_mkt_v (run ./build-plugin.sh to resync it)")

  if [ "${#mismatched[@]}" -gt 0 ]; then
    local joined
    joined="$(printf '; %s' "${mismatched[@]}")"
    die "manifest version mismatch — $PLUGIN_JSON says $canonical but ${joined:2}"
  fi

  printf '%s' "$canonical"
}

check_main_mode() {  # <current-version>
  local cur="$1" base
  if ! shipped_changed; then
    echo "bump: no shipped (plugin/, .claude-plugin/) change vs origin/main — OK"
    return 0
  fi
  base="$(_plugin_json_version_at "${BASE_REMOTE_REF}")"
  require_semver "$base"
  if semver_gt "$cur" "$base"; then
    echo "bump: shipped change vs origin/main; version $cur > $base — OK"
    return 0
  fi
  die "shipped (plugin/, .claude-plugin/) changed but version $cur is not > origin/main's $base" \
    "— bump plugin/.claude-plugin/plugin.json and plugin/.claude-plugin/marketplace.json, then run ./build-plugin.sh"
}

check_develop_mode() {  # <current-version>
  local cur="$1" base
  base="$(_plugin_json_version_at "${BASE_REMOTE_REF}")"
  require_semver "$base"
  if [ "$cur" = "$base" ]; then
    echo "bump: develop base; version $cur == origin/main's $base — OK"
    return 0
  fi
  die "develop never carries a version bump — version $cur must equal origin/main's $base" \
    "(a release PR, develop -> main, is what advances the version; back-merge main into develop to self-heal)"
}

main() {
  local mode="" base_ref=""
  while [ "$#" -gt 0 ]; do
    case "$1" in
      --check) mode="check"; shift ;;
      --base-ref)
        [ "$#" -ge 2 ] && [ -n "$2" ] || die "--base-ref requires a value"
        base_ref="$2"; shift 2 ;;
      *) usage ;;
    esac
  done
  [ "$mode" = "check" ] || usage

  if [ "${HAS_NO_RELEASE:-}" = "true" ]; then
    echo "bump: 'no-release' label present — version-bump gate waived."
    exit 0
  fi

  [ -n "$base_ref" ] || base_ref="${GITHUB_BASE_REF:-main}"

  ensure_base
  local cur
  cur="$(check_manifests_agree)"

  case "$base_ref" in
    main) check_main_mode "$cur" ;;
    develop) check_develop_mode "$cur" ;;
    *) die "unsupported --base-ref '$base_ref' (only main|develop are recognized)" ;;
  esac
}
main "$@"
